### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by tigerdan2** [ArekkuusuJerii/Solar#9]
1.12.2

only Improbable plot + mirror api (tried both versioN)

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/katsstuff/teamnightclipse/mirror/data/Vector3

**Comment by BunnyCinnamon** [comment]
Oh... do you have the file of the crash?

**Comment by BunnyCinnamon** [comment]
Use [Mirror-dev 1.12.2-0.3.0](https://dl.bintray.com/team-nightclipse/maven/net/katsstuff/teamnightclipse/mirror/1.12.2-0.3.0/mirror-1.12.2-0.3.0.jar) it is not in the curse page as of now.

Mirror itself crashes for some reason, so I guess it wont boot unless I go back to 0.2.0...
